### ISSUE TITLE
Problems with GDAL. Tried to install GDAL with pip but I couldn't

### ISSUE THREAD

**Issue by anyosa** [r-barnes/richdem#38]
Hi,
Do you have any advice to solve the GDAL problem? (I'm using macOS Catalina).
Thanks!

shasta_dem = rd.LoadGDAL(dem_path)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-bf11d29e6c4a>", line 1, in <module>
    shasta_dem = rd.LoadGDAL(dem_path)
  File "/usr/local/lib/python3.7/site-packages/richdem/__init__.py", line 255, in LoadGDAL
    raise Exception("richdem.LoadGDAL() requires GDAL.")
Exception: richdem.LoadGDAL() requires GDAL.

**Comment by giswqs** [comment]
Try using conda to install it. You will need [Anaconda](https://www.anaconda.com/distribution/#download-section) or [Miniconda](https://docs.conda.io/en/latest/miniconda.html) installed on your computer. 
```
conda create -n py38 python
conda activate py38
conda install -c conda-forge gdal richdem
```
